cp -r template object/data_required_for_the_final_certification_software/software_accomplishment_summary
cp -r template object/data_required_for_the_final_certification_software/software_configuration_index
cp -r template object/data_required_for_the_final_certification_software/software_configuration_management_records
cp -r template object/data_required_for_the_final_certification_software/software_life_cycle_environment_configuration_index
cp -r template object/data_required_for_the_final_certification_software/software_process_assurance_records
cp -r template object/data_required_for_the_final_certification_software/software_verification_results
cp -r template object/data_required_for_the_final_certification_software/problem_reports

cp -r template object/data_required_for_the_software_development/software_configuration_management_records
cp -r template object/data_required_for_the_software_development/software_design_data
cp -r template object/data_required_for_the_software_development/software_life_cycle_environment_configuration_index
cp -r template object/data_required_for_the_software_development/software_review_and_analysis_procedures
cp -r template object/data_required_for_the_software_development/software_review_and_analysis_results
cp -r template object/data_required_for_the_software_development/software_process_assurance_records
cp -r template object/data_required_for_the_software_development/software_requirements
cp -r template object/data_required_for_the_software_development/software_requirements_design_and_source_code_standards
cp -r template object/data_required_for_the_software_development/software_tool_qualification_data
cp -r template object/data_required_for_the_software_development/software_traceability_data
cp -r template object/data_required_for_the_software_development/programming_language
cp -r template object/data_required_for_the_software_development/problem_reports

cp -r template object/data_required_for_the_software_planning_review/software_configuration_management_plan
cp -r template object/data_required_for_the_software_planning_review/software_design_plan
cp -r template object/data_required_for_the_software_planning_review/software_process_assurance_plan
cp -r template object/data_required_for_the_software_planning_review/software_process_assurance_records
cp -r template object/data_required_for_the_software_planning_review/software_requirements_design_source_code_validation_and_verification_and_archive_standards
cp -r template object/data_required_for_the_software_planning_review/software_validation_plan
cp -r template object/data_required_for_the_software_planning_review/software_verification_plan
cp -r template object/data_required_for_the_software_planning_review/plan_for_software_aspects_of_certification
cp -r template object/data_required_for_the_software_planning_review/supplier_management_plan
cp -r template object/data_required_for_the_software_planning_review/tool_qualification_plans

cp -r template object/data_required_for_the_software_verification/software_configuration_management_records
cp -r template object/data_required_for_the_software_verification/software_design_representation_data
cp -r template object/data_required_for_the_software_verification/software_life_cycle_environment_configuration_index
cp -r template object/data_required_for_the_software_verification/software_process_assurance_records
cp -r template object/data_required_for_the_software_verification/software_requirements_data
cp -r template object/data_required_for_the_software_verification/software_tool_qualification_data
cp -r template object/data_required_for_the_software_verification/software_verification_procedures
cp -r template object/data_required_for_the_software_verification/software_verification_results
cp -r template object/data_required_for_the_software_verification/programming_language
cp -r template object/data_required_for_the_software_verification/problem_reports


cp -r template review/data_required_for_the_final_certification_software/software_accomplishment_summary
cp -r template review/data_required_for_the_final_certification_software/software_configuration_index
cp -r template review/data_required_for_the_final_certification_software/software_configuration_management_records
cp -r template review/data_required_for_the_final_certification_software/software_life_cycle_environment_configuration_index
cp -r template review/data_required_for_the_final_certification_software/software_process_assurance_records
cp -r template review/data_required_for_the_final_certification_software/software_verification_results
cp -r template review/data_required_for_the_final_certification_software/problem_reports

cp -r template review/data_required_for_the_software_development/software_configuration_management_records
cp -r template review/data_required_for_the_software_development/software_design_data
cp -r template review/data_required_for_the_software_development/software_life_cycle_environment_configuration_index
cp -r template review/data_required_for_the_software_development/software_review_and_analysis_procedures
cp -r template review/data_required_for_the_software_development/software_review_and_analysis_results
cp -r template review/data_required_for_the_software_development/software_process_assurance_records
cp -r template review/data_required_for_the_software_development/software_requirements
cp -r template review/data_required_for_the_software_development/software_requirements_design_and_source_code_standards
cp -r template review/data_required_for_the_software_development/software_tool_qualification_data
cp -r template review/data_required_for_the_software_development/software_traceability_data
cp -r template review/data_required_for_the_software_development/programming_language
cp -r template review/data_required_for_the_software_development/problem_reports

cp -r template review/data_required_for_the_software_planning_review/software_configuration_management_plan
cp -r template review/data_required_for_the_software_planning_review/software_design_plan
cp -r template review/data_required_for_the_software_planning_review/software_process_assurance_plan
cp -r template review/data_required_for_the_software_planning_review/software_process_assurance_records
cp -r template review/data_required_for_the_software_planning_review/software_requirements_design_source_code_validation_and_verification_and_archive_standards
cp -r template review/data_required_for_the_software_planning_review/software_validation_plan
cp -r template review/data_required_for_the_software_planning_review/software_verification_plan
cp -r template review/data_required_for_the_software_planning_review/plan_for_software_aspects_of_certification
cp -r template review/data_required_for_the_software_planning_review/supplier_management_plan
cp -r template review/data_required_for_the_software_planning_review/tool_qualification_plans

cp -r template review/data_required_for_the_software_verification/software_configuration_management_records
cp -r template review/data_required_for_the_software_verification/software_design_representation_data
cp -r template review/data_required_for_the_software_verification/software_life_cycle_environment_configuration_index
cp -r template review/data_required_for_the_software_verification/software_process_assurance_records
cp -r template review/data_required_for_the_software_verification/software_requirements_data
cp -r template review/data_required_for_the_software_verification/software_tool_qualification_data
cp -r template review/data_required_for_the_software_verification/software_verification_procedures
cp -r template review/data_required_for_the_software_verification/software_verification_results
cp -r template review/data_required_for_the_software_verification/programming_language
cp -r template review/data_required_for_the_software_verification/problem_reports
